### ISSUE TITLE
Delete all but the main 3 paths on SingPath

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#139]
Now that students can solve SingPath problems, let's remove all of the paths other than the three supported paths that show up in the SingPath section of the ClassMentors profile. It should be easy for users to find these three paths and solve problems. 

We should have already made it so that only the SingPath admin can make new paths. 

There will only be 3 SingPath paths for the foreseeable future. 
- python
- javascript
- angularjs

Each path will have a contribution level where the newly contributed problems will go until they are reviewed and moved into another level or deleted.

**Comment by dinoboff** [comment]
Done.

**Comment by SingaporeClouds** [comment]
I still see 2 paths not created by me. Can you double check that only the admin can create new paths and then delete the extra paths? 

![image](https://cloud.githubusercontent.com/assets/116418/9086640/2a57f300-3bb8-11e5-96b7-d1092f8e8a75.png)

**Comment by dinoboff** [comment]
It has been implemented for CM problem but not for Singpath.

I created a firebase rule for it (nobody can create a path except you), but I have to update the GUI so that button to create a new path doesn't show up to other users.

**Comment by dinoboff** [comment]
related #69
