### ISSUE TITLE
Unrecognised issue when defining a function named `product` in Python

### ISSUE THREAD

**Issue by blueset** [ChrisBoesch/singpathfire#147]
cc @dinoboff /docker-code-verifier

Tested on [Python/Level 5/Product of range](http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SW-67bEcHGOSP6TA/problems/-Jo1SXDWTPs9V8fB7fwQ/play)

## Test 
```python
>>> product(2,6,2)
 48
>>> product(3,20,5)
 5616
>>> [product(x,y,z) for (x,y,z) in [(2,5,1),(4,8,3),(12,150,6),(-4,856,8),(-2300,-4,45)]]
 [120, 28, 73498028204106382571065303804793585664000000L, -11417976085004829877143484096534834761338639789383649822360266805463639438299963897386542220380138938048953407314530197789647884393389414008234406303767430256531900827294450149827775559195261129192650510722843921015369124764604866534272978124800000000000000000000000000L, 26144042748299467669910003732581423525036602373811865193404050476269856050943027863188605120849609375000000000000000000000000000000000000000000000000000L]
```

## Solution
```python
def product(x,y,z):
    return 0
```

## Error message
`invalid syntax (<string>, line 1)`

## Other tests
* `def product1(a,b,c): pass` gives `product is not defined`
* `def product(): pass` gives `product requires 3 parameters`

**Comment by dinoboff** [comment]
@blueset it should be fixed

**Comment by blueset** [comment]
The issue persists. Tested on 15 Aug 2015 12:30.

![image](https://cloud.githubusercontent.com/assets/553831/9287482/74540a5a-4349-11e5-9220-0f39699bfa84.png)

**Comment by dinoboff** [comment]
The test was expecting python2 `long` type when there's only one type of integer in python3.

It's fixed now. However the results as a formatting issue: the last line is too long.

**Comment by dinoboff** [comment]
Closing. Reopen if you are having any issue with that problem.
